spring:
#   main:
#    allow-circular-references: true
  datasource:
    hikari:
      jdbc-url: "jdbc:mysql://localhost:3306/itsgood_ru?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 20
      driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: DownLoadMaster5781440
    url: "jdbc:mysql://localhost:3306/itsgood_ru?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      properties:
        hibernate:
          current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baseline-description: Flyway Scripts
#    locations: classpath:/db.migration
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    url: ${spring.datasource.url}
#    default-schema: public --неправильно
#    out-of-order: true
#    ignore-migration-patterns: '*:ignored'

---

amazon:
  images:
    s3: 123123213
    token: someToken
    password: password

---

google:
  servers:
    port: 8080
    name: some-server

---

jwtconfig:
 secret: secret
 expiration: 60000


