#    customize each one
spring:
  cache:
    caffeine:
      cache-names: role, contract, item, category, address, payment, delivery
        spec: maximumSize:100, expireAfterAccess=2s, initialCapacity=10
