#    customize each one
spring:
  cache:
    caffeine:
      cache-names: role, contract, item, category, address, payment, delivery
        spec: maximumSize:20, expireAfterAccess=10s, initialCapacity=10
